###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

/**:
  ros__parameters:

    version: 1.1.1
    terminal_output: true
    adaptive: true

    pointcloud:
      deskew: true
      voxelize: true

    imu:
      calibration: true
      intrinsics:
        accel:
          bias: [ 0.0, 0.0, 0.0 ]
          sm: [ 1.,  0.,  0.,
                0.,  1.,  0.,
                0.,  0.,  1. ]
        gyro:
          bias: [ 0.0, 0.0, 0.0 ]

    extrinsics:
      baselink2imu:
        t: [ -0.013, 0.012, 0.106 ]
        R: [ 1.,  0.,  0.,
              0.,  1.,  0.,
              0.,  0.,  1. ]
      baselink2lidar:
        t: [ 0.001, 0.0, 0.091 ]
        R: [ 1.,  0.,  0.,
              0.,  1.,  0.,
              0.,  0.,  1. ]
